### ISSUE TITLE
jfltexx - no sound after kernel update

### ISSUE THREAD

**Issue by marcusguita** [semsevens/nethunter_kernel_jfltexx#2]
**Device:**
Galaxy S4 (Intl) jfltexx

**OS version (KitKat/Lollipop/Marshmallow/Nougat):**
cm-13.0-20160820-SNAPSHOT-ZNH5YAO0J3-jfltexx

**Built from repo (date and build command) or downloaded from website (links):**
https://idlekernel.com/nethunter/nightly/3.15.2-20161002-0200/

**Output of cat /proc/version in adb shell or NetHunter Terminal:**
Linux version 3.4.107-nethunter-jfltexx-g5a41f24-dirty (semsevens@Dark) (gcc version 4.9.4 20150629 (prerelease) (crosstool-NG 1.20.0 - Linaro GCC 2015.06 - Cortex-A15) ) #1 SMP PREEMPT Sat Jun 4 22:05:33 CST 2016

**Issue:**
No sound after update kernel: kernel-nethunter-jfltexx-marshmallow-3.15.2-20161002-0200

**Comment by semsevens** [comment]
@marcusguita 
Sorry for coming late.
I just rebuild the kernel and fix it.
I have sent a PR. Just wait for a while.

**Comment by DeStilleGast** [comment]
I can confirm that this is fixed on Resurecion remix (latest marshmallow) with kernel: kernel-nethunter-jfltexx-marshmallow-3.15.3-20161126-1805

**Comment by marcusguita** [comment]
Yes!!! Could close this issue. Its perfect now!!! Thanks @semsevens, you are the best!!
